project_id = "pbjyudhxnhtxiblhkwgh"

[functions.print-ticket]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.license-proxy]
verify_jwt = false
